### ISSUE TITLE
Why Rust instead of WASM (or similar)?

### ISSUE THREAD

**Issue by rishflab** [theseus-os/Theseus#324]
I do not know much about OS dev so this may be a dumb question. 

Why have you selected Rust to isolate processes as opposed to a low level byte code (eg. WASM) that supports bounds checking? As far as I understand the you do not need the affine type system of Rust to ensure process isolation. You only need to ensure one process does not access resources that belong to another process which can be achieved with WASM, which "compiles" faster than safe Rust and is supported a compile target by other languages.

Ring0 SIP OS projects that use WASM:
https://github.com/tomaka/redshirt
https://github.com/nebulet/nebulet

**Comment by kevinaboos** [comment]
Not a dumb question! 

I don't know much about WASM, but from what I've heard, it requires an underlying runtime layer, e.g., a browser (?). Not entirely sure... could be an interesting direction to explore, but it's not my current focus. Also, I started this project before WASM was popular, so that's probably as good of a reason as any.

I don't have time myself to explore using WASM or compiling this codebase down to WASM, but I'd be willing to help out folks who are interested in it.
