### ISSUE TITLE
why not merge your efforts with redox os effort?

### ISSUE THREAD

**Issue by omac777** [theseus-os/Theseus#326]
There existed another project called redox os
https://github.com/redox-os/redox

You have plenty of really intelligent people in your team and you and the redox-os are like-minded in that you both want to create a rust-based operating system.

Why didn't you decide to collaborate with the redox-os project to gain that synergy?

I must admit I do prefer your Theseus-os build system, and redox os could benefit from this.  Theseus-os could benefit from other advances made on the redox-os front as well, i.e. gui/relibc.

I certainly appreciate the separating of the building of the docs and the book with "make doc" and "make book".  It makes the "make run" build duration quite short and snappy.  From what I experienced less than 2 minutes.  Traditional Unix builds with "make all" always include the building of docs so you've shortened the build time cycle on that front I find.  Hats off to you for that.

The build duration of redox-os is over an hour and fetches sources/binaries from a large number of different repositories.
So what am I saying?  Theseus wins on the build strategy front for sure.  That said redox-os capabilities I believe are more sophisticated and envisioned a great deal about how to integrate traditional unix like tools onto their os preserving a great degree of interoperability which is important.  Redox-os can inherit a great degree of goodness found in the Unix/Linux land because of this approach and could be integrated into production sooner as a result.  Building redox-os currently is very tricky.  They could use help in this regard.  They could also use help to make the build of everything faster.  Theseus has something to contribute on that front.

**Comment by kevinaboos** [comment]
Hi @omac777, thanks for the question! I'm indeed aware of redox, which is a super impressive and extensive line of work, as well as a variety of other Rust-based systems. The main purpose of Theseus is to support the exploration of various OS research goals rather than to achieve Unix-like or POSIX interface compatibility. As such, the core structure of Redox as a more conventional microkernel or a hybrid small monolithic kernel that realizes isolation based on hardware protection mechanisms like privilege modes and address spaces is incompatible with some of Theseus’s goals, therefore it's not possible to merge them. If, in the future, Theseus wishes to support legacy programs via a traditional userspace (in the ancient past we once did have partial support for that), then I think starting with redox's relibc and its userspace frameworks would be a great idea, but that's not currently on our agenda.

I appreciate the compliments, but I don't think it's fair to compare our build times to that of redox. Theseus is far smaller than redox, and that's why the build times differ; I doubt neither redox nor Theseus is doing anything special or clever with the build system.
