### ISSUE TITLE
Create hierarchy for book source files.

### ISSUE THREAD

**Issue by apogeeoak** [theseus-os/Theseus#399]
Following the recommendations from the mdBook [formatting chapter](https://rust-lang.github.io/mdBook/format/summary.html), I would like to propose an alternate structure for the book source files.

```
# The Theseus OS Book

## Introduction to Theseus
[Introduction to Theseus OS](README.md)

## Design and Structure of Theseus
- [Design and Structure of Theseus](design/README.md)
    - [Source Code Repository Organization](design/source_code_organization.md)
    - [Boot-up Procedure](design/booting.md)
    - [Safe-language OS Principles](design/idea.md)
    - [Intralingual Design]()

## Application Development
- [Developing a Theseus Application](app/README.md)
```

`README.md` files are converted into `index.html` files in the build output. No content would need to be changed. The only modifications would be file renames. An alternate naming scheme incorporating the chapter could also be used, `ch01-design/README.md`.

**Comment by kevinaboos** [comment]
I like it, thanks for recommending this @apogeeoak. I think we intended to organize the book files into directories like this, but never got around to it. 

Personally, I'm more in favor of organizing them according to content rather than chapter order, since that avoids having to rename a bunch of files if we decide to change the order of chapters in the future. 

I'd be happy to accept a PR that re-organizes the book similarly to what you showed above.
