### ISSUE TITLE
`target` and  `build` directory leak into the docker container

### ISSUE THREAD

**Issue by zetanumbers** [theseus-os/Theseus#426]
Hi. I tried to use docker method, but got an error where `demangle_readelf_file` requires `GLIBC_2.33` from `libc.so.6`. The problem is that Ubuntu 18.04 only supports `GLIBC_2.27`.

**Comment by kevinaboos** [comment]
Hi @ZetaNumbers, thanks for the issue report! 

That's odd, I'm running both Ubuntu 18.04 and 20.04 and I don't have any issues, but I also don't use the docker image. My version of glibc is 2.31, which works without problems. 

I'll take a look at your PR as well. Thanks!

**Comment by zetanumbers** [comment]
Uh, my bad, sorry. I tried to have clean docker build an it worked. I believe this is because cached compiler artifacts (target directory probably) had leaked into the container. The funny thing is that it's the same x86_64-unknown-linux-gnu target (and maybe even a fingerprint), but slightly different artifacts.

My suggestion would be to remove build and target dir right before the docker run, or specify some different directories to use (which i would prefer).

**Comment by kevinaboos** [comment]
haha, thanks, and no worries. There's a semi-related issue (#421) introduced by one of my latest changes, but it's not docker-specific. That will be addressed shortly. 

Regarding the sharing of target and build directories with the container and host, that behavior is intentional. It allows you to keep all build dependencies within the container, but then exit the container after the build completes and run the built version of Theseus on your host (e.g., using KVM for acceleration). This functionality was necessary for easily reproducing our benchmarks for our prior academic publications.
