### ISSUE TITLE
Update of vendored crates

### ISSUE THREAD

**Issue by zetanumbers** [theseus-os/Theseus#432]
`x86_64` crate stuck on a 2017 version. Should there be like a bot to update a fork? Dependabot? I would like to know what would be the preferred strategy there?

**Comment by kevinaboos** [comment]
We generally update crates when needed or when demonstrably beneficial, e.g., when updating to a newer rustc version.

In the specific case of `x86_64`, the direction that crate went diverged from and was incompatible with our design choices, and we've made significant changes to our fork and other experimental forks. I plan to eventually remove the dependency on `x86_64` entirely, mostly to accommodate a better design for handling MSRs, interrupts, and control registers, but also because we don't have any significant need to use it any more.

We're happy to accept PRs updating crate versions for a particular reason, such as `cargo audit` identifying a flaw in a third-party crate.
