### ISSUE TITLE
[SOLVED] version conflict while running `make run`

### ISSUE THREAD

**Issue by criticic** [theseus-os/Theseus#454]
```
Updating crates.io index
error: failed to select a version for the requirement `spin = "=0.5.2"`
candidate versions found which didn't match: 0.9.0
location searched: crates.io index
required by package `lazy_static v1.4.0`
    ... which is depended on by `acpi v0.1.0 (/home/username/Projects/Theseus/kernel/acpi)`
make: *** [Makefile:211: cargo] Error 101

**Comment by kevinaboos** [comment]
Hi @criticic, thanks for filing this issue!

I checked out a clean build of Theseus and built it in a new Ubuntu 20.04 VM, and I didn't encounter any build issues. Since I wasn't able to reproduce this, could you help me by providing some information about your build/host environment?

In the mean time, perhaps you can try a clean build (`make clean`) of a fresh copy of Theseus? It seems like the Cargo.lock file on your system may have been corrupted or modified.

Kindly do let me know if you're able to fix it and what the solution was. Thanks!

**Comment by criticic** [comment]
@kevinaboos you were right! apparently my `~/.cargo/registry`  dir got corrupted.  Clearing it and reinstalling all dependencies solved my issues

**Comment by criticic** [comment]
@kevinaboos is there a IRC/Matrix server for theseus?

**Comment by kevinaboos** [comment]
> @kevinaboos you were right! apparently my `~/.cargo/registry` dir got corrupted. Clearing it and reinstalling all dependencies solved my issues

Oh very interesting, I hadn't heard of that problem occurring before. Glad you were able to resolve this.

**Comment by kevinaboos** [comment]
> @kevinaboos is there a IRC/Matrix server for theseus?

We don't have a public discussion forum at the moment, no. I could look into starting either a gitter or discord server, if there's a need for it.
