### ISSUE TITLE
Bytes are being dropped by cat command -- likely an issue with applications/app_io or libs/stdio

### ISSUE THREAD

**Issue by vikrammullick** [theseus-os/Theseus#473]
The 256th (indexed at 0) byte is being dropped when writing to stdout (and possibly when reading from stdin though this hasn't been tested).

To reproduce, run `cat` on a text file that is longer than 256 bytes to observe that every 256th byte is dropped.

It seems likely that this is an off-by-one error either in `applications/app_io` or `libs/stdio`.

**Comment by kevinaboos** [comment]
Ok, finally found the culprit! (Took me a while since i wasn't the original author of that stdio code)

The code responsible for this is in the `try_read()` function here: https://github.com/theseus-os/Theseus/blob/18ea998fe7f69a13cb555547ef7a51452513a07c/libs/stdio/src/lib.rs#L255

Basically, it unconditionally pops the front item off of the stdio buffer, even when there is no next item in the buffer. 

The fix is to only call `pop_front()` iff there is another element in the destination `buf`.

I am fixing this for now since it's an obvious bug. Also, note that a full stdio redesign is in the works too, which will be more akin to an arbitrary byte stream, so this code will eventually be removed anyway.
