### ISSUE TITLE
[applications/shell] Shell panics in Shell::eval_cmdline().

### ISSUE THREAD

**Issue by ghost** [theseus-os/Theseus#567]
https://github.com/theseus-os/Theseus/blob/585ab93e0505f9ac8385764ed4353c8271b80d83/applications/shell/src/lib.rs#L688-L721

```Rust
let command = args.remove(0); 
```
This panics if args.len()==0.
So shell input(cmdline) like
```
|
```
and

``` 
X | 
```
  cause panic at args.remove().

I think the priority for this is low for now.
So I just leave an issue here.

**Comment by kevinaboos** [comment]
thanks for reporting this @yingwei9! We haven't devoted a lot of time to the `shell` since it will be eventually removed in favor of a proper terminal emulator, but it'd still be good to fix this in the meantime.

If you'd like to submit a fix for this, that'd be greatly appreciated; I'd be happy to review a PR. Otherwise we can leave it open and see if anyone wants to tackle it.
