### ISSUE TITLE
Undefined behaviour in `MappedPages::as_type(_mut)`

### ISSUE THREAD

**Issue by tsoutsman** [theseus-os/Theseus#791]
The bytes are uninitialised, so it is undefined behaviour to interpret them as anything, even if they can hold any fixed bit pattern ([3rd invariant](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#initialization-invariant)).

Zeroing the memory when allocating would work, or marking the functions as unsafe with the requirement that they have been initialised.

**Comment by kevinaboos** [comment]
Closing as the title of this is a bit misleading and implies that there is an actual flaw in those functions. Also, the underlying problem is almost certainly unavoidable; see [discussion on Discord here](https://discord.com/channels/977298261566181456/978760398952079461/1061461995200716851).

Will follow-up with Ralf Jung in the future to see if he has recommendations
