### ISSUE TITLE
About SGX application in Theseus

### ISSUE THREAD

**Issue by fantas1a** [theseus-os/Theseus#844]
Hi, because I want to use SGX in Theseus, may I know if I can use [qemu-sgx](https://github.com/intel/qemu-sgx) to substitude qemu/qemu-system to run Theseus? Cloud you please give me any suggestions or ideas? Thanks very much.

**Comment by kevinaboos** [comment]
Hi @fantas1a, thanks for the question! I don't have any experience with SGX, but I'm fairly confident you wouldn't be able to simply use a different QEMU binary, since any bare-metal OS like Theseus must be compiled for and execute on a specific architecture and target.

SGX isn't something we have explored in Theseus, so I'm not sure how it would be incorporated into our various system/hardware components.
