### ISSUE TITLE
Question: application upd

### ISSUE THREAD

**Issue by mdochdev** [theseus-os/Theseus#902]
In the application directory there is an application called upd. This appears to allow for the OS to have individual shared crates updated, provided I build the server the right way. 

Q: Is there an example of what the update server would look like which holds these crates? 
Q: Is the build process for the crates the same or different from the initial building?
Q: Do I have to always build these updates from the same tree (to avoid linking issues)

I am investigating running a micro server that uses shared crates from a default running application, and this project looks like it would fit the bill, not having to build an OS from scratch, networking is the biggest pain to get right. Kind of how docker was designed to work, a single process running in a container. 

I would be stripping the "captain" down to just kick off my process in headless mode (for release not debug). No console / shell etc...

I am currently toying with a few ideas:
- Having the server itself build its own updates based on inputs which replace the existing library. Will be hard as I need to port the rust compiler and work out how to get the llvm there as well.
- Having the server request an update from an external update server which would build a new crate and ship it down. This looks supported. 
It is unclear if the process is running if it would need to cycle itself to pick-up the new crate (shared). Lazy loading, does it get swapped out of memory when de-referenced.

Worst case options:
- I could build a WASM file either externally or internally (I would need to port the compiler) and pull that locally and reuse the wasm application.
- I write my own DSL for updates and handle the updates internally.

I am planning on the OS being a completely closed system that only has a WebAPI JSON interface. Each server will play by its own rules, so an update will be specific to that server. But with a common set of APIs. The server will decide how to change its own rules based on existing ones and the input, these rules will drive the output for the APIs.

In the early stages of planning and trying to understand if the size of the idea is do-able for me. I may need to make some concessions around how the rules are updated / stored and generated. Depending on the outcome of the responses. IE: Going down the DSL route and parsing it on the fly.

**Comment by kevinaboos** [comment]
Hi @mdochdev, thanks for the interest in Theseus and for the great questions!

In brief, the `upd` app and live evolution functionality has fallen out of focus lately, but we would definitely like to continue that feature direction and not let it get too stale.

> Q: Is there an example of what the update server would look like which holds these crates?

Yep, the latest example of that is fairly old at this point, but it is described in great detail as part of our OSDI'20 paper's evaluation, which you can see here: https://github.com/theseus-os/Theseus/tree/osdi20ae/osdi20ae

> Q: Is the build process for the crates the same or different from the initial building?

It's the same, but you need to run an additional make command after you apply the changes to the tree; see the above link for more details. The relevant targets are also described in the `Makefile`, see the `build_server` target.

> Q: Do I have to always build these updates from the same tree (to avoid linking issues)

The build environment needs to be identical; you may be able to build it from 2 identical trees but it'd be best and easiest to build it from the same tree to ensure it works.

> I would be stripping the "captain" down to just kick off my process in headless mode (for release not debug). No console / shell etc...

Yep, sounds good. We've started some work on a headless mode of Theseus for this exact use case, but it's still a WIP. 
We have always wanted to make Theseus really easy to configure, but haven't yet spent a great deal of time on that. However, it should be relatively simple given our architecture of many small crates; it should be possible to choose a specific set of crates by specifying a Cargo featureset or a Cargo package, though I haven't tried that myself yet. We plan to try this out  in the near future for easy configuration of OS builds across x86 and aarch64 too.

> Having the server itself build its own updates based on inputs which replace the existing library. Will be hard as I need to port the rust compiler and work out how to get the llvm there as well.

That's going to be exceedingly difficult and would likely represent years of work. Instead, I'd just recommend serving updates OTA from another host machine, which is how we did it for the examples in the above link.

> It is unclear if the process is running if it would need to cycle itself to pick-up the new crate (shared). Lazy loading, does it get swapped out of memory when de-referenced.

Depends on the runtime context of what was changed. You're correct in saying that updating and replacing a given crate in memory will not directly and automatically cause all dependent crates to update and re-run any sort of code that depends on things that had changed. For example, if you issue a live update for a component that only runs once during early bootstrap/init, then that update won't actually have any effect on the running system since it won't be re-run. For things that run continually/periodically, they should be able to use the new functionality on their next loop; similarly, an application may need to be killed and restarted depending on the scope of its modifications. I believe this is generally discussed in our paper and in my dissertation sections about live evolution and the inherent limitations therein. Currently this is all manually specified, but we are definitely interested in making it more automated and easier to specify.

-----------

Regarding the rest of your requirements, yes, I think Theseus would be appropriate for your use case. Note that things are still under heavy development, so some features you'd expect to see in a mature OS may not be complete yet, but we are happy to address certain requests and also help with integrating any contributions you may be interested in making.
